### ISSUE TITLE
It does not work well when children is scrollview component. Please advice.

### ISSUE THREAD

**Issue by hiteshagja** [DuDigital/react-native-zoomable-view#16]
I have scrollview component inside zoomable view and it's working fine in Android but in iOS it's not. Basically zoomable view working fine perfectly but that scrollview content is lagging now when I normally scroll.

Please advice for best solution.

**Comment by SimonErich** [comment]
Hello @hiteshagja,
i did take a look at that, but I don't think there is something we can do (easily) to fix this problem, because we need the movement gestures to work for the shifting and pinching gestures.
I also can't image a scenario where this would make sense from a user perspective to combine scrollview inside the zoom.
Can you maybe show us your usecase? Maybe we can find a way around this?

**Comment by skantus** [comment]
@hiteshagja an idea is check when the zoom is started maybe you could use `onZoomBefore` to disable the `Scrollview` using `scrollEnabled` then you can validate when `initialZoom` will `0` you turn on `scrollEnabled` to start scrolling.

This is a hacky way but can works.

Hope it's help.

**Comment by hiteshagja** [comment]
@skantus Thanks for your reply.

It was my bad that I have not noticed scrollview has it's own zoom handler(for ios). So no need to wrap scrollview inside zoomview. For android I had already done what you said and it's working OK, can't say fine but acceptable. 

I hope my comment and @skantus comment will help others.

**Comment by skantus** [comment]
@hiteshagja that's true, optionally there are other ways to do it, I paste a related issue in Android.

https://github.com/facebook/react-native/issues/20154#issuecomment-420562297
