### ISSUE TITLE
React-native-zoomable-view in a swiper

### ISSUE THREAD

**Issue by lahwran** [DuDigital/react-native-zoomable-view#5]
So I hear from the README that this is a todo. I'd really love to have an example of that :) What all needs to be customized to get the gestures to play nice?

**Comment by SimonErich** [comment]
@lahwran we are actually using this in production within a slider right now, but there are still some glitches and problems we are trying to figure out.
It doesn't work as smooth as we would like it to.

The way it currently works for us with [react-native-swiper](https://github.com/leecade/react-native-swiper ) is basically:
- Use the ReactNativeZoomableWithGestures component instead of the simple "ReactNativeZoomableWithGestures"
- we use the onZoomAfter and onDoubleTapAfter events to enable or disable the swiper (depending on whether zoomLevel > 1)

Right now we actually also added the possibility to swipe with a resistance, when we are zoomed in, but the solution is rather hackish.
We are working on refactoring this into a cleaner solution.

If all you need is a simple solution, that doesn't require you to change slides, while you are zoomed in, the approach above works very well.
If you need more than that, tell me again, and I will try to put something together from our code.
That might take a little bit tough.

**Comment by wesselstudios** [comment]
To add to this for reference, I encountered a similar issue while `ReactNativeZoomableView` was nested inside a `ViewPager` (from `@react-native-community/viewpager`). 

My solution was your second suggestion @SimonErich. I used event handlers to track whether or not zoomLevel was greater than 1, then disabled `scrollEnabled` when that was the case.

**Comment by milansusnjar** [comment]
@SimonErich Did you refactor this for a case when it's in a flat list?
I have this: 
```
<FlatList
horizontal={true}
pagingEnabled={true}
onScrollBeginDrag={handleScrollStart}
onMomentumScrollEnd={handleSwipeEnd}
renderItem={({ item }) => (
            <ReactNativeZoomableView
              maxZoom={2}
              minZoom={0.9}
              zoomStep={0.5}
              initialZoom={1}
              bindToBorders={true}
              captureEvent={true}
```
...

onZoomBefore I disable FlatList scroll
onZoomEnd I enable it if zoom is <= 1
onShiftingBefore I enable FlatList scroll if offsetX === lastX

and it almost works fine. One problem I can't fix when you move a zoomed image to the right border, and then it would swipe FlatList but you can swipe to the left and it won't pan the image, it will swipe FlatList to the previous image.
